### ISSUE TITLE
Tasks and Requirements

### ISSUE THREAD

**Issue by lucasdanielgeo** [lucasdanielgeo/turismo-dev#1]
## Tasks

- [ ] Form Viagens

   - [ ] Structure the form;
      - [ ] Form contexts based on user country:
         - [ ] Brazilian documents;
         - [ ] Not Brasil: Specified documents;
      - [ ]  Form contexts based on user age;
         - [ ] If user is under 18 years old, ask for specified documents
         - [ ] If user is above  18 years old, ask for specified documents

   - [ ] Selo da viagem
      - [ ] Gerar PDF com QRCode;
      - [ ] Enviar para o email do contratante;   

- [ ] Plataforma de gerenciamento
   - [ ] Listar viagens cadastradas

- [ ] Database
   - [x] Create Role
   - [x] Create table
